apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ro2jr5r1g-go 
  janus-idp.io/tekton: ro2jr5r1g-go
  backstage.io/kubernetes-id: ro2jr5r1g-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ro2jr5r1g-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  